[package]
name = "thesauromatic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paw = "1.0.0"
phf = "0.10.0"
toml = "0.5.8"

[build-dependencies]
phf_codegen = "0.10.0"
