[package]
name = "thesauromatic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = "0.10.0"

[build-dependencies]
phf_codegen = "0.10.0"
